language: node_js
node_js:
  - "4"
  - "node"
dist: trusty
script:
  - bash ./test/test.sh
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
